version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql-go-crm
    restart: always
    environment:
      MYSQL_DATABASE: 'db-crm'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      # Where our data will be persisted
      - my-db:/var/lib/mysql
volumes:
  # Names our volume
  my-db:
